---
title: "What you’ve missed in R"
author: "Alastair Rushworth"
date: "10/06/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Motivation 

September this year marks the 10 full years of my use of R, and while reflecting on this point, it occured to me that I've learnt as much or more about the language during the second half of this period than the first.  The language itself like others such as Python is surfing a tidal wave of enthusiasm caused by the ubiquity of data and the need for analytics, taking it from the relative obscurity of the academic statistics community to mainstream use in many corportate environments.  When I started writing R code in 2007, data science did not exist and R was not a hot skill.  

Against the backdrop of this, the language has also undergone an explosive level of development by it's user community evidenced by the near explonential growth in R packages over the same period.  CRAN is just the tip of the iceberg of R development here, with GitHub, BioConductor, rOpenSci, CrossValidated and a constellation of blogs all testament to the enthusiasm of R's development.  It seems that the breadth of development has increased particularly over the last few years, and R has diversified as a language that previously only served statistics - the challenge then is to keep updated.  Many established users (like myself) have an ingrained workflow that works for them, and without effort, it can be difficult to change old habits, or event to recognise that there are alterntives.  The list below is my response to this challenge - it's a list of things that I would have liked a tutorial on over the past few years, and describe the ways in which R is becoming a much more powerful language.


## 1. RStudio

This list is not a ranked list, but I've deliberately placed RStudio at the beginning.  For those that don't know, RStudio is THE development environment for R, began in XXXX and is developed by some of the top data scientists and most prolific R developers in the world.  If you aren't using RStudio already, then you really should be, especially if you use RGui to write code.  The main benefit of RStudio is an increase in the speed with which you'll write your code - there are so many ways that the environment oils the wheels of this.  Almost every R user can benefit from using RStudio.
[RStudio gif]
As the name suggests, RStudio is developed specifically for R development and offers a script editor with the usual code completion, syntax highlighting, programmable keyboard shortcuts, help with profiling, clever integration with package development, close integration with shiny and markdown, git.  RStudio is free to download, can be hosted in the cloud with server edition.  

## 2. 
